from __future__ import annotations

import io
import math
import os
import re
from typing import Any, Literal

import pandas as pd
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
from scipy import stats
from sympy import latex, sqrt, symbols
try:
    from anthropic import Anthropic
except ImportError:  # pragma: no cover - deployed via requirements.txt
    Anthropic = None
from dotenv import load_dotenv

load_dotenv()

app = FastAPI(title="PL Protocol Scientific Backend")
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

OMEGA_EARTH_RAD_PER_S = 7.2921159e-5
FORBIDDEN_SUMMARY_TERMS = [
    "PL Generator", "Codex", "Claude", "Anthropic", "localhost", "Proxy",
    "SHA256", "Python-Analyse", "internal provenance", "serverseitig", "generated by",
]

AnalysisType = Literal["table", "figure", "result", "calculation", "warning"]

class AnalyzeRequest(BaseModel):
    csv: str = Field(..., min_length=1)
    filename: str | None = None
    metadata: dict[str, Any] | None = None
    notes: str | None = None

class GenerateRequest(BaseModel):
    model: str = "claude-sonnet-4-5"
    max_tokens: int = 12000
    system: str
    messages: list[dict[str, Any]]


def _analysis_item(*, item_id: str, item_type: AnalysisType, title: str, description: str, include_default: bool = True, essential: bool = False, data: Any = None, latex_hint: str = "") -> dict[str, Any]:
    return {"id": item_id, "type": item_type, "title": title, "description": description, "include_default": include_default, "essential": essential, "data": data, "latex_hint": latex_hint}


def _read_table(raw: str) -> pd.DataFrame:
    if not raw.strip():
        raise ValueError("Leere Messdatei.")
    
    # Try common delimiters explicitly before fallback to auto-detection
    delimiters = [",", ";", "\t"]
    df = None
    last_error = None
    
    for delim in delimiters:
        try:
            df = pd.read_csv(io.StringIO(raw), sep=delim, engine="python")
            if not df.empty:
                break
        except Exception as e:
            last_error = e
            continue
    
    # If explicit delimiters failed, try auto-detection
    if df is None or df.empty:
        try:
            df = pd.read_csv(io.StringIO(raw), sep=None, engine="python")
        except Exception as exc:
            raise ValueError(f"CSV/TXT konnte nicht vollständig gelesen werden: {exc}") from exc
    
    if df.empty:
        raise ValueError("Die Datei enthält keine auswertbaren Datenzeilen.")
    return df


def _numeric_frame(df: pd.DataFrame) -> pd.DataFrame:
    converted = pd.DataFrame(index=df.index)
    for col in df.columns:
        s = df[col]
        if s.dtype == object:
            s = s.astype(str).str.replace(",", ".", regex=False)
        converted[col] = pd.to_numeric(s, errors="coerce")
    return converted


def _stats_table(num: pd.DataFrame) -> tuple[list[str], list[dict[str, Any]]]:
    numeric_cols = [c for c in num.columns if num[c].notna().any()]
    rows: list[dict[str, Any]] = []
    for col in numeric_cols:
        s = num[col].dropna().astype(float)
        n = int(s.size)
        sd = float(s.std(ddof=1)) if n > 1 else None
        sem = float(sd / math.sqrt(n)) if sd is not None and n > 0 else None
        rows.append({"column": str(col), "n": n, "mean": float(s.mean()) if n else None, "sample_std_ddof1": sd, "sem": sem, "min": float(s.min()) if n else None, "max": float(s.max()) if n else None})
    return [str(c) for c in numeric_cols], rows


def _find_column(columns: list[str], patterns: list[str]) -> str | None:
    for c in columns:
        cl = c.lower()
        if any(re.search(p, cl) for p in patterns):
            return c
    return None


def _linear_regression(num: pd.DataFrame) -> dict[str, Any] | None:
    cols = [str(c) for c in num.columns]
    time_col = _find_column(cols, [r"^t$", r"time", r"zeit"])
    angle_col = _find_column(cols, [r"angle", r"winkel", r"phi", r"varphi"])
    if not time_col or not angle_col:
        return None
    pair = num[[time_col, angle_col]].dropna().astype(float)
    if len(pair) < 2:
        return None
    x = pair[time_col].to_numpy(dtype=float)
    y = pair[angle_col].to_numpy(dtype=float)
    lr = stats.linregress(x, y)
    return {"x_column": time_col, "y_column": angle_col, "n": int(len(pair)), "slope": float(lr.slope), "intercept": float(lr.intercept), "r_value": float(lr.rvalue), "r_squared": float(lr.rvalue**2), "p_value": float(lr.pvalue), "stderr": float(lr.stderr)}


def _latitude_result(regression: dict[str, Any] | None, metadata: dict[str, Any] | None) -> dict[str, Any] | None:
    if not regression:
        return None
    meta = metadata or {}
    omega = meta.get("omega_mess_rad_s")
    explicit = False
    if omega is None and str(meta.get("angle_unit", "")).lower() in {"rad", "radian", "rad/s"}:
        omega = regression["slope"]
        explicit = True
    elif omega is not None:
        explicit = True
    if not explicit:
        return {"not_computable": True, "reason": "Breitengrad nicht berechenbar: Winkeleinheit bzw. omega_mess_rad_s wurde nicht explizit bereitgestellt.", "correction_factor_used": False}
    ratio = float(omega) / OMEGA_EARTH_RAD_PER_S
    if abs(ratio) > 1:
        return {"not_computable": True, "reason": "Breitengrad nicht berechenbar: omega_mess / Omega_Erde liegt außerhalb des Definitionsbereichs von arcsin.", "omega_mess_rad_s": float(omega), "correction_factor_used": False}
    return {"not_computable": False, "omega_mess_rad_s": float(omega), "omega_earth_rad_s": OMEGA_EARTH_RAD_PER_S, "ratio": ratio, "latitude_deg": float(math.degrees(math.asin(ratio))), "correction_factor_used": False}


def _formula_item() -> dict[str, Any]:
    x, dx, y, dy = symbols("x Delta_x y Delta_y", positive=True)
    expr = sqrt(dx**2 + dy**2)
    return _analysis_item(item_id="gaussian_error_template", item_type="calculation", title="Symbolische Fehlerfortpflanzung", description="Allgemeines Sympy-Beispiel für quadratische Gaußsche Fehlerfortpflanzung mit Sympy-LaTeX-Export.", data={"latex": latex(expr)})


def _clean_summary(obj: dict[str, Any]) -> dict[str, Any]:
    text = repr(obj)
    if any(term.lower() in text.lower() for term in FORBIDDEN_SUMMARY_TERMS):
        raise ValueError("Interne Provenienzbegriffe dürfen nicht in summary_for_generation erscheinen.")
    return obj


@app.post("/api/analyze")
def analyze(req: AnalyzeRequest) -> dict[str, Any]:
    try:
        df = _read_table(req.csv)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc

    num = _numeric_frame(df)
    numeric_cols, stat_rows = _stats_table(num)
    row_count = int(len(df))
    column_count = int(len(df.columns))
    missing_total = int(df.isna().sum().sum())

    tables: list[dict[str, Any]] = []
    figures: list[dict[str, Any]] = []
    results: list[dict[str, Any]] = []
    calculations: list[dict[str, Any]] = []
    warnings: list[dict[str, Any]] = []

    tables.append(_analysis_item(item_id="raw_statistics", item_type="table", title="Statistik der Messspalten", description="Zeilenanzahl, Mittelwert, Stichprobenstandardabweichung, SEM, Minimum und Maximum für alle numerischen Spalten.", data=stat_rows))
    results.append(_analysis_item(item_id="dataset_overview", item_type="result", title="Datenbasis", description="Die Rohdaten wurden vollständig eingelesen und tabellarisch ausgewertet.", essential=True, data={"rows": row_count, "columns": column_count, "missing_values": missing_total}))

    regression = _linear_regression(num)
    if regression:
        calculations.append(_analysis_item(item_id="angular_regression", item_type="calculation", title="Lineare Winkelregression", description="Deterministische lineare Regression für erkannte Zeit-Winkel-Paare mit Slope, Intercept, R² und p-Wert.", data=regression))
        figures.append(_analysis_item(item_id="angle_time_plot", item_type="figure", title="Winkel-Zeit-Diagramm", description="Pgfplots-kompatible Koordinaten der ausgewerteten Zeit- und Winkelwerte mit Regressionsgerade.", data={"x_col": regression.get("x_column"), "y_col": regression.get("y_column"), "slope": regression.get("slope")}))
    else:
        warnings.append(_analysis_item(item_id="no_time_angle_regression", item_type="warning", title="Keine Zeit-Winkel-Regression", description="Es wurden keine eindeutig benannten Zeit- und Winkelspalten gefunden.", data={"not_computable": True, "requires_todo": True}))

    cols_lower = {str(c).lower() for c in df.columns}
    has_x = any(c in cols_lower or "x" == c for c in cols_lower)
    has_y = any(c in cols_lower or "y" == c for c in cols_lower)
    if has_x and has_y and not regression:
        warnings.append(_analysis_item(item_id="xy_tracking_no_angle", item_type="warning", title="x/y-Tracking ohne definierte Winkeltransformation", description="Aus x/y-Spuren wurde kein physikalischer Winkel berechnet; eine explizite Transformation ist erforderlich.", data={"not_computable": True, "requires_todo": True}))

    latitude = _latitude_result(regression, req.metadata)
    if latitude:
        results.append(_analysis_item(item_id="latitude_result", item_type="result", title="Breitengrad aus Winkelgeschwindigkeit", description="Berechnung nur bei explizit definierter Winkelgeschwindigkeit oder Winkeleinheit möglich.", data=latitude))

    calculations.append(_formula_item())
    for name in ["calibration", "pendulum_length", "frame_rate", "mass", "device_parameters"]:
        if not (req.metadata or {}).get(name):
            warnings.append(_analysis_item(item_id=f"missing_{name}", item_type="warning", title=f"Fehlender Parameter: {name}", description=f"{name} wurde nicht in den Metadaten bereitgestellt.", data={"not_computable": True}))

    summary_for_generation = _clean_summary({"used_all_rows": True, "row_count": row_count, "column_count": column_count, "detected_numeric_columns": numeric_cols, "selected_item_rule": "Only selected items from tables, figures, results, calculations listed here."})
    return {"used_all_rows": True, "row_count": row_count, "column_count": column_count, "detected_numeric_columns": numeric_cols, "tables": tables, "figures": figures, "results": results, "calculations": calculations, "warnings": warnings, "summary_for_generation": summary_for_generation}


@app.post("/api/generate")
def generate(req: GenerateRequest) -> dict[str, Any]:
    api_key = os.getenv("ANTHROPIC_API_KEY")
    if not api_key:
        raise HTTPException(status_code=500, detail="ANTHROPIC_API_KEY ist nicht konfiguriert.")
    if Anthropic is None:
        raise HTTPException(status_code=500, detail="anthropic package ist nicht installiert.")
    client = Anthropic(api_key=api_key)
    msg = client.messages.create(model=req.model, max_tokens=req.max_tokens, system=req.system, messages=req.messages)
    return {"content": [block.model_dump() for block in msg.content]}
