from __future__ import annotations

import io
import json
import math
import os
import re
from typing import Any, Literal

import pandas as pd
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
from scipy import stats
from sympy import latex, sqrt, symbols
try:
    from anthropic import Anthropic
except ImportError:  # pragma: no cover - deployed via requirements.txt
    Anthropic = None
from dotenv import load_dotenv

load_dotenv()

app = FastAPI(title="PL Protocol Scientific Backend")
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

OMEGA_EARTH_RAD_PER_S = 7.2921159e-5
FORBIDDEN_SUMMARY_TERMS = [
    "PL Generator", "Codex", "Claude", "Anthropic", "localhost", "Proxy",
    "SHA256", "Python-Analyse", "internal provenance", "serverseitig", "generated by",
]
RAW_GENERATION_KEYS = {"raw_csv", "csv", "file_content"}

AnalysisType = Literal["table", "figure", "result", "calculation", "warning"]

class AnalyzeRequest(BaseModel):
    csv: str = Field(..., min_length=1)
    filename: str | None = None
    metadata: dict[str, Any] | None = None
    notes: str | None = None

class GenerateRequest(BaseModel):
    model: str = "claude-sonnet-4-5"
    max_tokens: int = 12000
    system: str | None = None
    messages: list[dict[str, Any]] | None = None
    experiment_title: str | None = None
    experiment_type: str | None = None
    lab_notes: str | None = None
    metadata: dict[str, Any] | None = None
    summary_for_generation: dict[str, Any] | str | None = None
    selected_analysis_blocks: list[dict[str, Any]] | None = None
    generation_rules: dict[str, Any] | None = None
    raw_csv: str | None = None
    csv: str | None = None
    file_content: str | None = None


def _analysis_item(*, item_id: str, item_type: AnalysisType, title: str, description: str, include_default: bool = True, essential: bool = False, data: Any = None, latex_hint: str = "") -> dict[str, Any]:
    return {"id": item_id, "type": item_type, "title": title, "description": description, "include_default": include_default, "essential": essential, "data": data, "latex_hint": latex_hint}


def build_preview_blocks(analysis: dict[str, Any]) -> list[dict[str, Any]]:
    sections = {
        "tables": "Tabellen",
        "figures": "Abbildungen",
        "results": "Messergebnisse",
        "calculations": "Rechnungen",
        "warnings": "Warnungen",
    }
    blocks: list[dict[str, Any]] = []
    for source_array, section in sections.items():
        for item in analysis.get(source_array, []) or []:
            item_id = str(item.get("id") or f"{source_array}_{len(blocks) + 1}")
            blocks.append({
                "id": item_id,
                "type": item.get("type") or source_array.rstrip("s"),
                "section": section,
                "title": item.get("title") or item_id,
                "content": {
                    "description": item.get("description", ""),
                    "data": item.get("data"),
                    "latex_hint": item.get("latex_hint", ""),
                },
                "source": {"array": source_array, "id": item_id},
            })
    return blocks


def _strip_raw_generation_fields(value: Any, warnings: list[str], path: str = "") -> Any:
    if isinstance(value, dict):
        cleaned: dict[str, Any] = {}
        for key, item in value.items():
            key_path = f"{path}.{key}" if path else str(key)
            if str(key) in RAW_GENERATION_KEYS:
                warnings.append(f"Rohdatenfeld ignoriert: {key_path}")
                continue
            cleaned[key] = _strip_raw_generation_fields(item, warnings, key_path)
        return cleaned
    if isinstance(value, list):
        return [_strip_raw_generation_fields(item, warnings, f"{path}[]") for item in value]
    return value


def _preferred_generation_payload(req: GenerateRequest) -> dict[str, Any]:
    return {
        "experiment_title": req.experiment_title,
        "experiment_type": req.experiment_type,
        "lab_notes": req.lab_notes,
        "metadata": req.metadata or {},
        "summary_for_generation": req.summary_for_generation,
        "selected_analysis_blocks": req.selected_analysis_blocks or [],
        "generation_rules": req.generation_rules or {},
    }


def _uses_preferred_generation_payload(req: GenerateRequest) -> bool:
    return any([
        req.experiment_title,
        req.experiment_type,
        req.lab_notes,
        req.metadata,
        req.summary_for_generation,
        req.selected_analysis_blocks,
        req.generation_rules,
    ])


def _build_llm_request(req: GenerateRequest) -> tuple[str, list[dict[str, Any]], list[str]]:
    warnings: list[str] = []
    for raw_key in RAW_GENERATION_KEYS:
        if getattr(req, raw_key) is not None:
            warnings.append(f"Rohdatenfeld ignoriert: {raw_key}")

    system = req.system or (
        "Erstelle ein LaTeX-Protokoll ausschliesslich aus summary_for_generation, "
        "selected_analysis_blocks, Metadaten, lab_notes und generation_rules. "
        "Rohdaten duerfen nicht verwendet werden."
    )

    if _uses_preferred_generation_payload(req):
        payload = _strip_raw_generation_fields(_preferred_generation_payload(req), warnings)
        return system, [{"role": "user", "content": [{"type": "text", "text": json.dumps(payload, ensure_ascii=False, indent=2)}]}], warnings

    if not req.messages:
        raise HTTPException(status_code=422, detail="messages oder bevorzugter Generate-Payload erforderlich.")
    messages = _strip_raw_generation_fields(req.messages, warnings)
    return system, messages, warnings


def _numeric_series(series: pd.Series) -> pd.Series:
    """Convert a measurement column to numbers, accepting decimal commas."""
    normalized = series.astype("string").str.strip().str.replace(",", ".", regex=False)
    return pd.to_numeric(normalized, errors="coerce")


def _score_delimiter(df: pd.DataFrame) -> float:
    """Score a parsed DataFrame for plausibility. Higher is better."""
    if df.empty:
        return -1.0

    num_cols = len(df.columns)
    if num_cols == 0:
        return -1.0

    converted = pd.DataFrame(index=df.index)
    for col in df.columns:
        converted[col] = _numeric_series(df[col])

    numeric_cols = sum(1 for c in converted.columns if converted[c].notna().any())
    empty_cols = sum(1 for c in converted.columns if converted[c].isna().all())
    non_numeric_cols = num_cols - numeric_cols
    return numeric_cols * 10.0 - empty_cols * 5.0 - non_numeric_cols * 2.0


def _first_nonempty_line(raw: str) -> str:
    for line in raw.splitlines():
        if line.strip():
            return line.strip()
    return ""


def _read_table(raw: str) -> pd.DataFrame:
    if not raw.strip():
        raise ValueError("Leere Messdatei.")

    header = _first_nonempty_line(raw)
    common_delimiters = [",", ";", "\t"]
    header_delimiters = [d for d in common_delimiters if d in header]
    # If the header declares a field separator, decimal separators in data rows
    # must not compete as delimiters. This is essential for semicolon-separated
    # European measurement files with decimal commas.
    delimiters = header_delimiters or common_delimiters
    candidates: list[tuple[float, str, pd.DataFrame]] = []

    for delim in delimiters:
        try:
            df = pd.read_csv(io.StringIO(raw), sep=delim, engine="python")
            if df.empty:
                continue
            expected_cols = header.count(delim) + 1 if delim in header else 1
            if delim in header and len(df.columns) != expected_cols:
                continue
            score = _score_delimiter(df)
            candidates.append((score, delim, df))
        except Exception:
            continue

    if candidates:
        candidates.sort(reverse=True, key=lambda x: x[0])
        best_score, _best_delim, best_df = candidates[0]
        if best_score >= 0:
            return best_df

    if not header_delimiters:
        try:
            df = pd.read_csv(io.StringIO(raw), sep=None, engine="python")
            if not df.empty and _score_delimiter(df) >= 0:
                return df
        except Exception:
            pass

    raise ValueError("CSV/TXT konnte nicht vollständig gelesen werden: Keine plausible Spaltenstruktur gefunden.")


def _numeric_frame(df: pd.DataFrame) -> pd.DataFrame:
    converted = pd.DataFrame(index=df.index)
    for col in df.columns:
        converted[col] = _numeric_series(df[col])
    return converted


def _stats_table(num: pd.DataFrame) -> tuple[list[str], list[dict[str, Any]]]:
    numeric_cols = [c for c in num.columns if num[c].notna().any()]
    rows: list[dict[str, Any]] = []
    for col in numeric_cols:
        s = num[col].dropna().astype(float)
        n = int(s.size)
        sd = float(s.std(ddof=1)) if n > 1 else None
        sem = float(sd / math.sqrt(n)) if sd is not None and n > 0 else None
        rows.append({"column": str(col), "n": n, "mean": float(s.mean()) if n else None, "sample_std_ddof1": sd, "sem": sem, "min": float(s.min()) if n else None, "max": float(s.max()) if n else None})
    return [str(c) for c in numeric_cols], rows


def _column_profile(df: pd.DataFrame, num: pd.DataFrame) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    rows: list[dict[str, Any]] = []
    warnings: list[dict[str, Any]] = []
    for col in df.columns:
        raw = df[col]
        numeric = num[col]
        non_missing = raw.dropna()
        non_missing_count = int(non_missing.size)
        numeric_count = int(numeric.notna().sum())
        text_count = int(non_missing_count - numeric_count)
        missing_count = int(raw.isna().sum())
        unique_count = int(non_missing.nunique())
        is_constant = bool(non_missing_count > 0 and unique_count == 1)

        if non_missing_count == 0:
            inferred_type = "empty"
        elif numeric_count == non_missing_count:
            inferred_type = "numeric"
        elif numeric_count == 0:
            inferred_type = "text"
        else:
            inferred_type = "mixed"

        rows.append({
            "column": str(col),
            "inferred_type": inferred_type,
            "non_missing_count": non_missing_count,
            "missing_count": missing_count,
            "numeric_count": numeric_count,
            "text_count": text_count,
            "unique_count": unique_count,
            "is_constant": is_constant,
        })

        if inferred_type == "empty":
            warnings.append(_analysis_item(item_id=f"empty_column_{col}", item_type="warning", title=f"Leere Spalte: {col}", description="Diese Spalte enthält keine auswertbaren Werte.", data={"column": str(col)}))
        elif inferred_type == "mixed":
            warnings.append(_analysis_item(item_id=f"mixed_column_{col}", item_type="warning", title=f"Gemischte Spalte: {col}", description="Diese Spalte enthält sowohl numerische als auch textuelle Werte.", data={"column": str(col)}))
        elif inferred_type == "numeric" and is_constant:
            warnings.append(_analysis_item(item_id=f"constant_numeric_column_{col}", item_type="warning", title=f"Konstante numerische Spalte: {col}", description="Diese numerische Spalte besitzt keine Variation.", data={"column": str(col)}))

    return rows, warnings


def _missing_values_summary(df: pd.DataFrame) -> dict[str, Any]:
    per_column = {str(col): int(df[col].isna().sum()) for col in df.columns}
    return {"total_missing_values": int(sum(per_column.values())), "missing_values_per_column": per_column}


def _find_column(columns: list[str], patterns: list[str]) -> str | None:
    for c in columns:
        cl = c.lower()
        if any(re.search(p, cl) for p in patterns):
            return c
    return None


def _rubensrohr_analysis(num: pd.DataFrame) -> dict[str, list[dict[str, Any]]] | None:
    cols = [str(c) for c in num.columns]
    frequency_col = _find_column(cols, [r"^frequency_hz$", r"^frequency$", r"^frequenz$", r"^f$", r"^f_hz$", r"^hz$"])
    spacing_col = _find_column(cols, [r"^peak_spacing_m$", r"^peak_spacing$", r"^spacing$", r"^abstand$", r"^maxima_abstand$", r"^flammen_abstand$", r"^d$", r"^d_m$"])
    if not frequency_col or not spacing_col:
        return None

    pair = num[[frequency_col, spacing_col]].dropna().astype(float)
    pair = pair[(pair[frequency_col] > 0) & (pair[spacing_col] > 0)]
    if len(pair) < 2:
        return {"tables": [], "figures": [], "results": [], "calculations": [], "warnings": [_analysis_item(item_id="rubensrohr_insufficient_data", item_type="warning", title="Rubensrohr-Auswertung nicht möglich", description="Frequenz- und Abstandsspalten wurden erkannt, aber weniger als zwei positive Wertepaare sind vorhanden.", data={"not_computable": True})]}

    frequency = pair[frequency_col]
    spacing = pair[spacing_col]
    wavelength = 2.0 * spacing
    sound_speed = frequency * wavelength
    n = int(sound_speed.size)
    sample_std = float(sound_speed.std(ddof=1)) if n > 1 else None
    sem = float(sample_std / math.sqrt(n)) if sample_std is not None else None

    x = 1.0 / frequency
    y = spacing
    lr = stats.linregress(x.to_numpy(dtype=float), y.to_numpy(dtype=float))

    table_rows = [
        {
            "frequency_Hz": float(f),
            "peak_spacing_m": float(d),
            "wavelength_m": float(w),
            "sound_speed_m_s": float(c),
        }
        for f, d, w, c in zip(frequency, spacing, wavelength, sound_speed, strict=True)
    ]
    coordinates = [{"inverse_frequency_s": float(inv_f), "peak_spacing_m": float(d)} for inv_f, d in zip(x, y, strict=True)]
    result_data = {
        "n": n,
        "mean_sound_speed_m_s": float(sound_speed.mean()),
        "sample_std_ddof1_m_s": sample_std,
        "sem_m_s": sem,
        "min_sound_speed_m_s": float(sound_speed.min()),
        "max_sound_speed_m_s": float(sound_speed.max()),
        "source_columns": {"frequency_Hz": frequency_col, "peak_spacing_m": spacing_col},
    }
    regression_data = {
        "model": "peak_spacing_m = slope * (1 / frequency_Hz) + intercept",
        "n": n,
        "slope": float(lr.slope),
        "intercept": float(lr.intercept),
        "slope_stderr": float(lr.stderr),
        "intercept_stderr": float(lr.intercept_stderr),
        "c_regression_m_s": float(2.0 * lr.slope),
        "c_regression_stderr_m_s": float(2.0 * lr.stderr),
        "r_squared": float(lr.rvalue**2),
        "p_value": float(lr.pvalue),
        "coordinates": coordinates,
    }

    return {
        "tables": [_analysis_item(item_id="rubensrohr_sound_speed_table", item_type="table", title="Rubensrohr-Schallgeschwindigkeit je Messpunkt", description="Wellenlänge und Schallgeschwindigkeit aus Frequenz und Maxima-Abstand.", data=table_rows, latex_hint="Tabelle mit frequency_Hz, peak_spacing_m, wavelength_m und sound_speed_m_s.")],
        "figures": [_analysis_item(item_id="rubensrohr_inverse_frequency_plot", item_type="figure", title="Rubensrohr: Abstand gegen inverse Frequenz", description="Pgfplots-kompatible Koordinaten für peak_spacing_m gegen 1/frequency_Hz.", data={"coordinates": coordinates, "x": "inverse_frequency_s", "y": "peak_spacing_m"})],
        "results": [_analysis_item(item_id="rubensrohr_sound_speed_result", item_type="result", title="Rubensrohr-Schallgeschwindigkeit", description="Mittelwert, Stichprobenstandardabweichung und SEM der berechneten Schallgeschwindigkeit.", essential=True, data=result_data)],
        "calculations": [_analysis_item(item_id="rubensrohr_inverse_frequency_regression", item_type="calculation", title="Rubensrohr-Regression über inverse Frequenz", description="Linearer Fit von peak_spacing_m gegen 1/frequency_Hz; c_regression = 2 * slope.", essential=True, data=regression_data)],
        "warnings": [],
    }


def _linear_regression(num: pd.DataFrame) -> dict[str, Any] | None:
    cols = [str(c) for c in num.columns]
    time_col = _find_column(cols, [r"^t$", r"time", r"zeit"])
    angle_col = _find_column(cols, [r"angle", r"winkel", r"phi", r"varphi"])
    if not time_col or not angle_col or time_col == angle_col:
        return None
    pair = num[[time_col, angle_col]].dropna().astype(float)
    if len(pair) < 2:
        return None
    x = pair[time_col].to_numpy(dtype=float)
    y = pair[angle_col].to_numpy(dtype=float)
    if len(set(x.tolist())) < 2:
        return None
    try:
        lr = stats.linregress(x, y)
    except ValueError:
        return None
    return {"x_column": time_col, "y_column": angle_col, "n": int(len(pair)), "slope": float(lr.slope), "intercept": float(lr.intercept), "r_value": float(lr.rvalue), "r_squared": float(lr.rvalue**2), "p_value": float(lr.pvalue), "stderr": float(lr.stderr)}


def _latitude_result(regression: dict[str, Any] | None, metadata: dict[str, Any] | None) -> dict[str, Any] | None:
    if not regression:
        return None
    meta = metadata or {}
    omega = meta.get("omega_mess_rad_s")
    explicit = False
    if omega is None and str(meta.get("angle_unit", "")).lower() in {"rad", "radian", "rad/s"}:
        omega = regression["slope"]
        explicit = True
    elif omega is not None:
        explicit = True
    if not explicit:
        return {"not_computable": True, "reason": "Breitengrad nicht berechenbar: Winkeleinheit bzw. omega_mess_rad_s wurde nicht explizit bereitgestellt.", "correction_factor_used": False}
    ratio = float(omega) / OMEGA_EARTH_RAD_PER_S
    if abs(ratio) > 1:
        return {"not_computable": True, "reason": "Breitengrad nicht berechenbar: omega_mess / Omega_Erde liegt außerhalb des Definitionsbereichs von arcsin.", "omega_mess_rad_s": float(omega), "correction_factor_used": False}
    return {"not_computable": False, "omega_mess_rad_s": float(omega), "omega_earth_rad_s": OMEGA_EARTH_RAD_PER_S, "ratio": ratio, "latitude_deg": float(math.degrees(math.asin(ratio))), "correction_factor_used": False}


def _formula_item() -> dict[str, Any]:
    x, dx, y, dy = symbols("x Delta_x y Delta_y", positive=True)
    expr = sqrt(dx**2 + dy**2)
    return _analysis_item(item_id="gaussian_error_template", item_type="calculation", title="Symbolische Fehlerfortpflanzung", description="Allgemeines Sympy-Beispiel für quadratische Gaußsche Fehlerfortpflanzung mit Sympy-LaTeX-Export.", data={"latex": latex(expr)})


def _clean_summary(obj: dict[str, Any]) -> dict[str, Any]:
    text = repr(obj)
    if any(term.lower() in text.lower() for term in FORBIDDEN_SUMMARY_TERMS):
        raise ValueError("Interne Provenienzbegriffe dürfen nicht in summary_for_generation erscheinen.")
    return obj


@app.post("/api/analyze")
def analyze(req: AnalyzeRequest) -> dict[str, Any]:
    try:
        df = _read_table(req.csv)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc

    num = _numeric_frame(df)
    numeric_cols, stat_rows = _stats_table(num)
    column_profile_rows, profile_warnings = _column_profile(df, num)
    missing_values = _missing_values_summary(df)
    row_count = int(len(df))
    column_count = int(len(df.columns))
    missing_total = int(missing_values["total_missing_values"])

    tables: list[dict[str, Any]] = []
    figures: list[dict[str, Any]] = []
    results: list[dict[str, Any]] = []
    calculations: list[dict[str, Any]] = []
    warnings: list[dict[str, Any]] = []

    tables.append(_analysis_item(item_id="raw_statistics", item_type="table", title="Statistik der Messspalten", description="Zeilenanzahl, Mittelwert, Stichprobenstandardabweichung, SEM, Minimum und Maximum für alle numerischen Spalten.", data=stat_rows))
    tables.append(_analysis_item(item_id="column_profile", item_type="table", title="Spaltenprofil", description="Erkannter Spaltentyp, fehlende Werte, numerische Werte, Textwerte und Konstantheit je Spalte.", include_default=False, data=column_profile_rows))
    results.append(_analysis_item(item_id="missing_values_summary", item_type="result", title="Fehlende Werte", description="Gesamtzahl und Verteilung fehlender Werte pro Spalte.", include_default=missing_total > 0, data=missing_values))
    results.append(_analysis_item(item_id="dataset_overview", item_type="result", title="Datenbasis", description="Die Rohdaten wurden vollständig eingelesen und tabellarisch ausgewertet.", essential=True, data={"rows": row_count, "columns": column_count, "missing_values": missing_total}))
    warnings.extend(profile_warnings)

    rubensrohr = _rubensrohr_analysis(num)
    regression = _linear_regression(num)
    has_known_physics = rubensrohr is not None or regression is not None
    if rubensrohr is not None:
        tables.extend(rubensrohr["tables"])
        figures.extend(rubensrohr["figures"])
        results.extend(rubensrohr["results"])
        calculations.extend(rubensrohr["calculations"])
        warnings.extend(rubensrohr["warnings"])

    if regression:
        calculations.append(_analysis_item(item_id="angular_regression", item_type="calculation", title="Lineare Winkelregression", description="Deterministische lineare Regression für erkannte Zeit-Winkel-Paare mit Slope, Intercept, R² und p-Wert.", data=regression))
        figures.append(_analysis_item(item_id="angle_time_plot", item_type="figure", title="Winkel-Zeit-Diagramm", description="Pgfplots-kompatible Koordinaten der ausgewerteten Zeit- und Winkelwerte mit Regressionsgerade.", data={"x_col": regression.get("x_column"), "y_col": regression.get("y_column"), "slope": regression.get("slope")}))
    elif _find_column([str(c) for c in num.columns], [r"^t$", r"time", r"zeit", r"angle", r"winkel", r"phi", r"varphi"]):
        warnings.append(_analysis_item(item_id="no_time_angle_regression", item_type="warning", title="Keine Zeit-Winkel-Regression", description="Es wurden keine eindeutig benannten Zeit- und Winkelspalten gefunden oder die unabhängige Variable besitzt keine Variation.", data={"not_computable": True, "requires_todo": True}))

    cols = [str(c) for c in df.columns]
    has_x = _find_column(cols, [r"^x$", r"^x_px$", r"x.*pixel", r"center.*x", r"^cx$"]) is not None
    has_y = _find_column(cols, [r"^y$", r"^y_px$", r"y.*pixel", r"center.*y", r"^cy$"]) is not None
    if has_x and has_y and not regression:
        has_known_physics = True
        warnings.append(_analysis_item(item_id="xy_tracking_no_angle", item_type="warning", title="x/y-Tracking ohne definierte Winkeltransformation", description="Aus x/y-Spuren wurde kein physikalischer Winkel berechnet; eine explizite Transformation ist erforderlich.", data={"not_computable": True, "requires_todo": True}))

    latitude = _latitude_result(regression, req.metadata)
    if latitude:
        results.append(_analysis_item(item_id="latitude_result", item_type="result", title="Breitengrad aus Winkelgeschwindigkeit", description="Berechnung nur bei explizit definierter Winkelgeschwindigkeit oder Winkeleinheit möglich.", data=latitude))

    if has_known_physics:
        calculations.append(_formula_item())
    if regression or has_x and has_y:
        for name in ["calibration", "pendulum_length", "frame_rate", "mass", "device_parameters"]:
            if not (req.metadata or {}).get(name):
                warnings.append(_analysis_item(item_id=f"missing_{name}", item_type="warning", title=f"Fehlender Parameter: {name}", description=f"{name} wurde nicht in den Metadaten bereitgestellt.", data={"not_computable": True}))
    if not has_known_physics:
        warnings.append(_analysis_item(item_id="ambiguous_physical_interpretation", item_type="warning", title="Keine physikalische Spezialauswertung", description="Die Datei wurde statistisch profiliert; ohne bekannten Spaltensatz wird keine physikalische Interpretation vorgenommen.", data={"not_computable": True}))

    summary_for_generation = _clean_summary({"used_all_rows": True, "row_count": row_count, "column_count": column_count, "detected_numeric_columns": numeric_cols, "selected_item_rule": "Only selected items from tables, figures, results, calculations listed here."})
    response = {"used_all_rows": True, "row_count": row_count, "column_count": column_count, "detected_numeric_columns": numeric_cols, "tables": tables, "figures": figures, "results": results, "calculations": calculations, "warnings": warnings, "summary_for_generation": summary_for_generation}
    response["preview_blocks"] = build_preview_blocks(response)
    return response


@app.post("/api/generate")
def generate(req: GenerateRequest) -> dict[str, Any]:
    api_key = os.getenv("ANTHROPIC_API_KEY")
    if not api_key:
        raise HTTPException(status_code=500, detail="ANTHROPIC_API_KEY ist nicht konfiguriert.")
    if Anthropic is None:
        raise HTTPException(status_code=500, detail="anthropic package ist nicht installiert.")
    system, messages, validation_warnings = _build_llm_request(req)
    client = Anthropic(api_key=api_key)
    msg = client.messages.create(model=req.model, max_tokens=req.max_tokens, system=system, messages=messages)
    content = [block.model_dump() if hasattr(block, "model_dump") else block for block in msg.content]
    return {"content": content, "validation_warnings": validation_warnings}
